server:
  port: 8080

#消息队列
spring:
  rabbitmq:
    host: 47.242.251.45
    port: 5672
    virtual-host: /
    username: admin
    password: 123456
    #开启消息二次确认,生产者到broker的交换机
    publisher-confirm-type: correlated
    #开启消息二次确认，交换机到队列的可靠性投递
    publisher-returns: true
    #为true,则交换机处理消息到路由失败，则会返回给生产者
    template:
      mandatory: true
      
mq:
  env: dev  
  config:
    exchange: order_exchange
    queue: order_queue
      